name: Generate Coverage Report

on: [pull_request, push]
    
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/provision-with-micromamba@v15

      - name: Pytest in conda environment
        run: |
          python -m pip install --no-deps .
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=hyp3_isce2 tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Generate README Badge
        run: |
          python -m pip install 
          coverate-badge -o images/coverage.svg

      - name: Commit README Badge
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update test coverage badge'
          add: 'images/coverage.svg'
