name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.20.0
    permissions: {}
    with:
      release_prefix: HyP3 ISCE2
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
