name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.7.1
    with:
      release_prefix: HyP3 ISCE2
      release_branch: main
      develop_branch: develop
      sync_pr_label: actions-bot
    secrets:
      USER_TOKEN: ${{ secrets.GITHUB_PAK }}
